### PR TITLE
CMake added

### PR DESCRIPTION
**Pull request by offa**
This PR addes cmake as a second build tool.

### Available:

- Building of library and apps
- Installation using `make install`
- Travis CI (Matrix using both)
- Generation of embedded content
- Testing compiler for `emplace()`
- Optional building / running of tests using gtest / gmock (default: `OFF`)
- Configure file - `Config.h` (based on a custom template in `cmake/`)

### Not (yet) available:
- Building tests on CI using cmake

Since google has merged gtest / gmock into one project - gmock depends on gtest though - i'm not sure how to handle this case on CI. It seems gmock requires gtest but doesn't ship it anymore in one bundle (?).

At the moment cmake will look for both if tests are enabled, otherwise there's no dependency on gtest / gmock if disabled.

### What's different to autoconf:

The cmake builds will use it's own `Config.h` (`cmake` directory); it has only a definition for `HAVE_UNORDERED_MAP_EMPLACE`, since i didn't see any usage of all the other flags. However, adding more options is simple enough.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks for this great contribution. I will take a proper look over the next
day or two!

**Comment by offa** [comment]
Great! :+1: 

With cmake i was able to cross-compile for an embedded Arm - seasocks works like a charm!

**Comment by mattgodbolt** [comment]
This is great stuff; thanks! I'll merge in and once we get a decent way of pointing at gmock I'll probably deprecate the old configure-based stuff in favour of CMake.

**Comment by mattgodbolt** [comment]
I've updated the main build to work with Catch.hpp instead of
google{test,mock}. I also hacked about a bit and added most of the things I
thought the CMake approach was missing; can you check it still works for
you here?

Thanks!

On Sun, Oct 18, 2015 at 7:21 AM, offa <notifications@github.com> wrote:

> Great! [image: :+1:]
>
> With cmake i was able to cross-compile for an embedded Arm - seasocks
> works like a charm!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/seasocks/pull/14#issuecomment-149006670>.
>



-- 
Matt

**Comment by offa** [comment]
Everything fine so far.

**Comment by offa** [comment]
Just one thing: It's a bit hard to figure out, where a build failure comes from currently.

**Comment by offa** [comment]
I have addressed this in #15.

**Comment by mattgodbolt** [comment]
Thanks! Merged :)

**Comment by offa** [comment]
@mattgodbolt Can we add an option for Tests, so they can (optionally) be turned off?

**Comment by mattgodbolt** [comment]
Certainly! Feel free to send a PR, else I'll try and get to it later this
week.

**Comment by offa** [comment]
Done: #20

**Pull request merged**
