### PR TITLE
CMake partial cleanup

### PR DESCRIPTION
**Pull request by dascandy**
- Makes the build run only once for the library
- Duplication removed
- Dead commands removed
- Include paths & library dependencies now propagate
- Enclosed the "embedded" logic into a single folder. Would be better still if you used the cmake function I sent on slack, but I have no time for that now.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks so much for the hard work!

Inevitably something funny has gone on with the CI build...I will take a look if you haven't got any immediate clues as to what's going on.

**Comment by mattgodbolt** [comment]
Ah! The issue is:
```
0.08s$ cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.3 or higher is required.  You are running version 3.2.2
```
We need to find a way to get a more up to date cmake in travis

**Comment by mattgodbolt** [comment]
http://www.sachinhandiekar.com/2016/03/building-c-project-on-travis-ci.html has some pointers on how to get newer cmakes

**Comment by mattgodbolt** [comment]
Ok I fixed everything up in trunk and will merge shortly!

**Comment by offa** [comment]
> Makes the build run only once for the library

Oh dear ... didn't notice that so far …

**Pull request merged**
