### PR TITLE
Seasocks now compiles in Windows with c++17 and VS2019

### PR DESCRIPTION
**Pull request by sjk7**
I have been as careful as I can about the changes so as to hopefully not break the Linux compile. At least on WSL2 Linux, this code compiles and all tests pass.

Build process is exactly the same for Windows (mkdir build && cdbuild followed by cmake ../) as it is in Linux; except in the resulting build directory there will be Visual Studio solution files that will enable seasocks to be built and debugged in visual studio. Please note I only tried the static library builds.

Steve

### CODE REVIEW

**Comment by madebr** [comment]
Add this to `.github/workflows/ci.yml` to get CI working:
```yml
  build_msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        build_config:
          - {args: "-DDEFLATE_SUPPORT=OFF", config: "Debug"}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build
        run: |
            cmake . -Bbuild ${{ matrix.build_config.args }}
            cmake --build build --parallel --config ${{ matrix.build_config.config }}
      - name: Test
        run: |
            cd build
            cmake --build . --target test --config ${{ matrix.build_config.config }}
            ctest -D ExperimentalBuild -C ${{ matrix.build_config.config }}
            ctest -D ExperimentalMemCheck -C ${{ matrix.build_config.config }}
            # FIXME: use github actions for coverage: https://github.com/marketplace/actions/codecov
```

**Comment by sjk7** [comment]
> Add this to `.github/workflows/ci.yml` to get CI working:
> 
> ```yaml
>   build_msvc:
>     runs-on: windows-latest
>     strategy:
>       matrix:
>         build_config:
>           - {args: "-DDEFLATE_SUPPORT=OFF", config: "Debug"}
>     steps:
>       - uses: actions/checkout@main
>       - uses: actions/setup-python@v2
>         with:
>           python-version: '3.x'
>       - name: Build
>         run: |
>             cmake . -Bbuild ${{ matrix.build_config.args }}
>             cmake --build build --parallel --config ${{ matrix.build_config.config }}
>       - name: Test
>         run: |
>             cd build
>             cmake --build . --target test --config ${{ matrix.build_config.config }}
>             ctest -D ExperimentalBuild -C ${{ matrix.build_config.config }}
>             ctest -D ExperimentalMemCheck -C ${{ matrix.build_config.config }}
>             # FIXME: use github actions for coverage: https://github.com/marketplace/actions/codecov
> ```

ci now complains with: 
Invalid workflow file : .github/workflows/ci.yml#L51 You have an error in your yaml syntax on line 51
right where I pasted the new job :-(

**Comment by sjk7** [comment]
Thanks! Glad to be of service!

**Comment by mattgodbolt** [comment]
Sorry I hadn't merged this earlier! Yay!

**Pull request merged**
