### PR TITLE
Version define fixed

### PR DESCRIPTION
**Pull request by offa**
Just a correction to the definition of the version string. It's set to the correct target now.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Is version.h not used any more? Seems like it's unnecessary now.

**Comment by offa** [comment]
It's still in use within the library. The application `serve` didn't use it.

I'm not sure if it's still necessary as workaround for eclipse (as the comments in it say).

**Comment by offa** [comment]
Maybe it's reasonable to store it in a constant (`constexpr`) variable anyway?

**Comment by mattgodbolt** [comment]
I'd be happy for it to be in a static constexpr variable somewhere where
IDEs can see it.

**Comment by offa** [comment]
There's already a generated `Config.h`, perhaps we can use it for that. I'll have a look on that.

**Comment by offa** [comment]
I think we can drop `Version.h` and the version compile define.

**Comment by mattgodbolt** [comment]
Is this good to go now?

**Comment by offa** [comment]
Yes, everything done.

**Comment by mattgodbolt** [comment]
Perfect: thanks!

**Pull request merged**
