### PR TITLE
Resolved ignoring return value error

### PR DESCRIPTION
**Pull request by twanas**
Pull request for issue: Release mode build fails Werror-unused-result #114

### CODE REVIEW

**Comment by offa** [comment]
I'm afraid, this isn't so easy :-/

There was a previous error on alpine with this function (cf. #100). `strerror_r()` returns either a `char*` or `int`, depending on the system. It's hard to know what to do.

**Comment by offa** [comment]
@twanas unfortunately I can't reproduce the error (yet). 

Can you try following snipped:

```cpp
std::string getLastError() {
    char errbuf[1024];
    const auto ignore = strerror_r(errno, errbuf, sizeof(errbuf));
    static_cast<void>(ignore);
    return errbuf;
}
```

This should work with both return types and hopefully satisfy the warning.

**Comment by twanas** [comment]
Hi @offa 

Your revision works well. I have updated the pull request.

Thanks for your help.

**Comment by offa** [comment]
Perfect! It should work with both versions of `strerror_r()`.

**Pull request merged**
