### PR TITLE
Clang 13 and 14 CI builds

### PR DESCRIPTION
**Pull request by offa**
Adds builds for latest Clang versions.

Both issue an error due to possible UB though:

```
/home/runner/work/seasocks/seasocks/src/main/c/md5/md5.cpp:190:25: error: performing pointer subtraction with a null pointer may have undefined behavior [-Werror,-Wnull-pointer-subtraction]
            if (!((data - (const md5_byte_t*) 0) & 3)) {
                        ^ ~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Review by mattgodbolt — APPROVED** [review]
Thanks! The UB thing probably needs looking at; that md5 library is a bit of a dodgy copy/paster anyway!

**Comment by offa** [comment]
I have updated to latest release 2.13.9, since there's an issue related to `MINSIGSTKSZ` / `constexpr`.

**Comment by rayburgemeestre** [comment]
Hi guys,

I also ran into this issue today, I took a fix from: https://github.com/Haivision/srt/pull/2392 and at least that makes it compile again.
I don't know if you guys would like to apply the same fix, this is the diff

```
--- a/src/main/c/md5/md5.cpp
+++ b/src/main/c/md5/md5.cpp
@@ -79,6 +79,7 @@
 #include "md5/md5.h"
 
 #include <cstring>
+#include <cstdint>
 
 #undef BYTE_ORDER /* 1 = big-endian, -1 = little-endian, 0 = unknown */
 #ifdef ARCH_IS_BIG_ENDIAN
@@ -187,7 +188,7 @@ md5_process(md5_state_t* pms, const md5_byte_t* data /*[64]*/) {
          * On little-endian machines, we can process properly aligned
          * data without copying it.
          */
-            if (!((data - (const md5_byte_t*) 0) & 3)) {
+            if (!(uintptr_t(data) & 3)) {
                 /* data are properly aligned */
                 X = (const md5_word_t*) data;
             } else {
```

**Comment by offa** [comment]
Can you file a PR for this?

**Comment by rayburgemeestre** [comment]
Definitely, will do it later tonight!

**Comment by offa** [comment]
Thanks @rayburgemeestre, this PR is green now! :+1:

**Pull request merged**
